# The recommended basic settings for Grape-Pi
num_workers: 8
out_dir: results
metric_best: auc
dataset: # need to delete file in processed folder if change args under dataset category
  name: protein
  dir: data/yeast-ORBI
  rebuild: true
  numeric_columns:
  - protein_probability
  - mRNA
  task: node
  task_type: classification
  transductive: true
  transform: none
  encoder: false
  node_encoder: false
  edge_encoder: false
  split: [0.6, 0.2, 0.2] # train, val, test
share:
  dim_in: -1
  dim_out: 2  # dim_out 2 is for binary classification
train:
  grape_pi: gcnconv
  loss_pos_weight: -1.0
  batch_size: 1
  ckpt_period: 10
  ckpt_clean: false
  sampler: full_batch
  epoch_resume: 0
model:
  type: gnn
  loss_fun: binary_cross_entropy_with_weight
  # the weight is calculated by num_negative_sample/num_positive_sample
gnn:
  layers_pre_mp: 1
  layers_mp: 1
  layers_post_mp: 1
  dim_inner: 10
  layer_type: gcnconv # sageconv gcnconv
  stage_type: skipsum  # stack skipsum skipconcat
  batchnorm: false # batchnorm make things worse
  act: relu
  dropout: 0.3
  normalize_adj: false
  head: protein
optim:
  optimizer: adam
  base_lr: 0.001
  weight_decay: 5e-4
  max_epoch: 300
  # try not use schedule and check fluctuation of training curve
  scheduler: none

