accelerator: auto
benchmark: false
bn:
  eps: 1.0e-05
  mom: 0.1
cfg_dest: config.yaml
custom_metrics: []
dataset:
  cache_load: false
  cache_save: false
  dir: ../data/single-soft-label
  edge_dim: 128
  edge_encoder: false
  edge_encoder_bn: true
  edge_encoder_name: Bond
  edge_message_ratio: 0.8
  edge_negative_sampling_ratio: 1.0
  edge_train_mode: all
  encoder: false
  encoder_bn: true
  encoder_dim: 128
  encoder_name: db
  format: PyG
  label_column: protein_probability_soft_label
  label_table: none
  location: local
  name: protein
  node_encoder: false
  node_encoder_bn: true
  node_encoder_name: Atom
  numeric_columns:
  - protein_probability
  remove_feature: false
  resample_disjoint: false
  resample_negative: false
  shuffle_split: true
  split:
  - 0.6
  - 0.2
  - 0.2
  split_mode: random
  task: node
  task_type: classification_binary_soft_label
  to_undirected: false
  transductive: false
  transform: none
  tu_simple: true
devices: 1
gnn:
  act: relu
  agg: add
  att_final_linear: false
  att_final_linear_bn: false
  att_heads: 1
  batchnorm: false
  clear_feature: true
  dim_inner: 10
  dropout: 0.0
  head: protein
  keep_edge: 0.5
  l2norm: true
  layer_type: sageconv
  layers_mp: 1
  layers_post_mp: 1
  layers_pre_mp: 1
  msg_direction: single
  normalize_adj: false
  self_msg: concat
  skip_every: 1
  stage_type: skipsum
gpu_mem: false
mem:
  inplace: false
metric_agg: argmax
metric_best: auc
model:
  edge_decoding: dot
  graph_pooling: add
  loss_fun: cross_entropy
  match_upper: true
  size_average: mean
  thresh: 0.5
  type: gnn
num_threads: 6
num_workers: 8
optim:
  base_lr: 0.001
  lr_decay: 0.1
  max_epoch: 100
  momentum: 0.9
  optimizer: adam
  scheduler: none
  steps:
  - 30
  - 60
  - 90
  weight_decay: 0.0005
out_dir: results/gastric-graphsage-soft-label
print: both
round: 4
run_dir: results
seed: 0
share:
  dim_in: -1
  dim_out: 1
  num_splits: 1
tensorboard_agg: true
tensorboard_each_run: false
train:
  auto_resume: false
  batch_size: 128
  ckpt_clean: false
  ckpt_period: 10
  enable_ckpt: true
  epoch_resume: 0
  eval_period: 10
  grape_pi: graphsage
  iter_per_epoch: 32
  loss_pos_weight: -1.0
  neighbor_sizes:
  - 20
  - 10
  - 5
  node_per_graph: 32
  radius: extend
  sample_node: false
  sampler: neighbor
  skip_train_eval: false
  walk_length: 4
val:
  node_per_graph: 32
  radius: extend
  sample_node: false
  sampler: full_batch
view_emb: false
