# The recommended basic settings for GNN
out_dir: results
dataset:
  name: protein
  dir: /Users/cgu3/Library/CloudStorage/OneDrive-InsideMDAnderson/proteomics/project/PPI-for-protein-detection/data/test-data
  protein_filename: combined_protein_7103_processed.csv
  interaction_filename: STRING-interaction-swiss.csv
  task: node
  task_type: classification
  transductive: true
  transform: none
train:
  batch_size: 32
  eval_period: 20
  ckpt_period: 100
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 2
  layers_post_mp: 1
  dim_inner: 22
  layer_type: generalconv
  stage_type: stack
  batchnorm: false
  act: prelu
  dropout: 0.0
  agg: add
  normalize_adj: false
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 5
