# The recommended basic settings for GNN
num_workers: 8
out_dir: results
metric_best: auc
dataset: # need to delete file in processed folder if change args under dataset category
  name: protein
  dir: ../data/single-soft-label
  label_column: protein_probability_soft_label
  numeric_columns:
  - protein_probability
#  - mRNA_TPM
  rebuild: true
  task: node
  task_type: classification_binary_soft_label
  transductive: false
  transform: none
  encoder: false
  node_encoder: false
  edge_encoder: false
  split: [0.6, 0.2, 0.2] # train, val, test
share:
  dim_in: -1
  dim_out: 1
train:
  grape_pi: graphsage
  loss_pos_weight: -1.0
  batch_size: 128
  ckpt_period: 10
  ckpt_clean: false
  sampler: neighbor
  eval_period: 10
  neighbor_sizes: # sample 20 from 1-order neighbor and so on
  - 20
  - 10
  - 5
  epoch_resume: 0
model:
  type: gnn
  loss_fun: cross_entropy
  # the weight is calculated by num_negative_sample/num_positive_sample
gnn:
  layers_pre_mp: 0
  layers_mp: 1
  layers_post_mp: 1
  dim_inner: 20
  layer_type: sageconv # sageconv gcnconv
  stage_type: skipsum #skipsum skipconcat
  batchnorm: false
  act: relu
  dropout: 0.0
  normalize_adj: false
  head: protein
optim:
  optimizer: adam
  base_lr: 0.001
  weight_decay: 5e-4
  max_epoch: 100
  # try not use schedule and check fluctuation of training curve
  scheduler: none

