# The recommended basic settings for GNN
out_dir: results
accelerator: auto
dataset:
  format: PyG
  name: protein_batch
  dir: ./data/single
  numeric_params:
    - protein.avgMass
    - protein.MatchedProducts
    - protein.matchedPeptides
    - protein.digestPeps
    - protein.seqCover(%)
    - protein.MatchedPeptideIntenSum
    - protein.top3MatchedPeptideIntenSum
    - protein.MatchedProductIntenSum
    - protein.sumNumBYCalc
    - protein.sumNumBYPepFrag1
    - protein.falsePositiveRate
  task: node
  task_type: classification
  transductive: false
  transform: none
  encoder: false
  node_encoder: false
  edge_encoder: false
share:
  dim_in: 11
  dim_out: 2
train:
  batch_size: 128
  eval_period: 10
  ckpt_period: 10
  sampler: neighbor
  neighbor_sizes:
    - 20
    - 15
    - 10
    - 5
model:
  type: gnn
  loss_fun: binary_cross_entropy_with_weight
  # the weight is calculated by num_negative_sample/num_positive_sample
  loss_pos_weight: -1.0
gnn:
  layers_pre_mp: 1
  layers_mp: 2
  layers_post_mp: 1
  dim_inner: 22
  layer_type: sageconv
  stage_type: skipsum
  batchnorm: false
  act: relu
  dropout: 0.0
  agg: add # agg only work when layer_type is generalconv
  normalize_adj: false
  head: protein
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 50
  scheduler: none


